spring:
  profiles:
#    include: oauth
    include: oauth-example

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/annotation_api?serverTimezone=UTC&characterEncoding=UTF-8
    username: dayspring
    password: secret

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
